# -*- mode: python ; coding: utf-8 -*-

block_cipher = None

a = Analysis(
    ['src\\app.py'],
    pathex=['src'],
    binaries=[],
    datas=[
        ('src\\config.yaml', '.'),
        ('src\\core', 'src\\core'),
        ('src\\ui', 'src\\ui'),
        ('appimg.ico', '.'),
    ],
    hiddenimports=[
        'PySide6.QtCore',
        'PySide6.QtGui',
        'PySide6.QtWidgets',
        'PySide6.QtSvg',
        'yfinance',
        'pandas',
        'numpy',
        'requests',
        'beautifulsoup4',
        'lxml',
        'openpyxl',
        'aiohttp',
        'PyYAML',
        'dotenv',
        'sqlite3',
        'src.core.adapters.jpx_listed',
        'src.core.adapters.csv_source',
        'src.core.adapters.wikipedia_sp500',
        'src.core.adapters.nasdaq_txt',
        'src.core.domain.models',
        'src.core.domain.rule40',
        'src.core.application.screening_service',
        'src.core.application.export_service',
        'src.ui.main_window',
        'src.ui.widgets.side_bar',
        'src.ui.widgets.results_table',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)

pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.zipfiles,
    a.datas,
    [],
    name='Rule40Screener',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=False,  # GUIアプリなのでコンソールを非表示
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon='appimg.ico',
)
